variables:
  TF_ROOT: ${CI_PROJECT_DIR}/terraform
  TF_HTTP_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${CI_COMMIT_BRANCH}
  TF_STATE_NAME: ${CI_COMMIT_BRANCH}
  TF_CACHE_KEY: ${CI_COMMIT_BRANCH}

cache:
  key: "${TF_ROOT}"
  paths:
    - ${TF_ROOT}/.terraform/
    - ${TF_ROOT}/.terraform.lock.hcl

before_script:
  - cd ${TF_ROOT}

stages:
  - prepare
  - validate
  - build
  - deploy

init:
  stage: prepare
  tags:
    - shell
  script:
    - terraform init
    - terraform validate


validate:
  stage: validate
  tags:
    - shell
  script:
    - terraform validate


plan:
  stage: build
  artifacts:
    name: plan
    paths:
      - ${TF_ROOT}/plan.cache
    reports:
      terraform: ${TF_ROOT}/plan.json
  tags:
    - shell
  script:
    - terraform plan

apply:
  stage: deploy
  environment:
    name: production
  dependencies:
    - plan
  when: manual
  only:
    - master
      mn, rtfg
  tags:
    - shell
  script:
    - terraform apply
  artifacts:
    paths:
      - ${TF_ROOT}/.terraform
