variables:
  TF_ROOT: ${CI_PROJECT_DIR}/terraform
  TF_HTTP_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${CI_COMMIT_BRANCH}
  TF_STATE_NAME: ${CI_COMMIT_BRANCH}
  TF_CACHE_KEY: ${CI_COMMIT_BRANCH}
cache:
  key: "${TF_ROOT}"
  paths:
    - ${TF_ROOT}/.terraform/
    - ${TF_ROOT}/.terraform.lock.hcl
# Test
before_script:
  - cd ${TF_ROOT}

stages:
  - prepare
  - validate
  - build
  - deploy

.global:
  tags:
    - shell
  rules:
    - changes:
      - docs/*
      - .vscode/*
      - .github/*
      - README.md
      - LICENSE
      when: never
    - when: on_success

init:
  stage: prepare
  extends: .global
  script:
    - terraform init
    - terraform validate

validate:
  extends: .global
  stage: validate
  script:
    - terraform validate

plan:
  stage: build
  extends: .global
  artifacts:
    name: plan
    paths:
      - ${TF_ROOT}/plan.cache
    reports:
      terraform: ${TF_ROOT}/plan.json
  script:
    - terraform plan

apply:
  stage: deploy
  extends: .global
  environment:
    name: production
  dependencies:
    - plan
  script:
    - terraform apply -auto-approve
  rules:
      - when: manual

  artifacts:
    paths:
      - ${TF_ROOT}/.terraform
