---
version: '3'

vars:
  PROJECT_DIR:
    sh: "git rev-parse --show-toplevel"
  TERRAFORM_DIR: "{{.PROJECT_DIR}}/terraform"
  ANSIBLE_DIR: "{{.PROJECT_DIR}}/ansible"

includes:
  ansible: .taskfiles/ansible.yml
  docs: .taskfiles/docs.yml
  terraform: .taskfiles/terraform.yml
